### ISSUE TITLE
How to represent ambiguity?

### ISSUE THREAD

**Issue by andreasprlic** [ga4gh/vrs#239]
PMS2 has a highly similar pseudogene, called PMS2CL. The high sequence similarity between them has the consequence that sometimes it is not clear in which of the two locations a variant is located. Is there a mechanism to represent such ambiguity?

**Comment by reece** [comment]
We don't have that kind of ambiguity in VRS right now. I would love to hear suggestions.

Once you have the right concepts, it's easy to talk about concepts precisely. When we've considered imprecision and ambiguity, we've done so by being precise about the kind of ambiguity. For example, a location may have inner and out bounds, a sequence may use IUPAC ambiguity codes, or a repeat may be defined with a range of repeat counts.

However, when we've talked about more complex kinds of ambiguity, such as sequence similarity,it's been very difficult to pin down exactly what we mean.

The closest that we came to this particular problem is to talk about an ambiguous location that consisted of a set of locations, kinda like a dbSNP rsid. That location could be used as a location, so that an Allele might be defined once across a set of locations. The intent was really for genome and transcript aligned segments, but I suppose could be used (abused?) to represent sets of locations through paralogy.

**Comment by andreasprlic** [comment]
I am not sure we need to be able to represent an alignment. To start with, it might be sufficient to just add some kind of label to a location with tags such as "putative pseudogene", "putative gene conversion", "putative gene fusion".
