### ISSUE TITLE
RelativeCopyNumber

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#277]
Revisit Relative CopyNumber statements, as seen in cytogenetics resources and WRT X-chromosome abnormalities.

**Comment by ahwagner** [comment]
@mcannon068nw follow this thread.

**Comment by mbaudis** [comment]
+1

**Comment by mbaudis** [comment]
As mentioned in an exchange w/ @ahwagner the **representation of relative copy number states is essential** since:

* most analyses do not deliver copy number counts - in fact the use of "copies"  is extremely unusual
* CN estimates will be influenced by clonality, impurity and ploidy
* even correct CN counts can frequently (cancer genomes...) only be interpreted by knowing the base ploidy level

A main logical paradigm of CN analyses and representation is the _relative_ level with respect to a baseline (i.e. ploidy level). In cancer genomics there is pretty much consistent use of a limited set of CN levels:

* homozygous deletion (i.e. estimated 0 copies in any ploidy)
* deletion (i.e. fewer copies than the assumed baseline; `CN=1` for diploid)
* duplication / low level gain (i.e. one or few more copies than baseline; operationally one can assume this as "not more than a duplication of the base CN count", i.e. `4` in a diploid genome)
* amplification / high level gain : from ~5 to any number - possibly in the hundreds - of copies of a genomic region. However, there is no clear definition of an `amplification` threshold and some definitions may include the regionality and exclude e.g. events leading to multiple copies of a chromosome

In practice, the current lack of a relative indication of CN state prohibits the use of the schema for most real world applications representing CNV events (or require to use fake values).

#### Changes needed

1. a class describing the relative copy number state (REQUIRED)
2. a representation of the base copy number at the location in the given sample (OPTIONAL; e.g. 2 for autosomes in diploid cells, 1 for X/Y in males, 3 for a triploid cell line with e.g. 69,XXX etc.)

The best option would be to have an ontology for such classes & SO should be the place? However, CNV representation there is confusing & incomplete.

#### Minimal pseudo-ontology for CNVs

```
id: CNVO:000001
label: copy number assessment
  id: CNVO:000002
  label: base ploidy
   id: CNVO:000004
   label: copy-neutral loss of heterozygosity
  id: CNVO:000003
  label: copy number variation
    id: CNVO:000005
    label: copy number loss
      id: CNVO:000007
      label: low-level copy number loss
      id: CNVO:000008
      label: homozygous deletion
    id: CNVO:000006
    label: copy number gain
      id: CNVO:000009
      label: low-level copy number gain
      id: CNVO:000010
      label: genomic amplification
```

I'd be happy to help working on this & extremely flexible regarding solutions ...

**Comment by ahwagner** [comment]
I agree completely with @mbaudis above. I think this gets around many of the challenges of representing the assay signal (e.g. log2 ratios) and moves straight to the heart of what CNV callers predict. This is very VRS-like, in my opinion (we also avoid VAF / read depth / intensity metrics elsewhere in VRS).

+1 @mbaudis

**Comment by mbaudis** [comment]
As of January 18, 2022 the [`copy number assessment`](http://www.ebi.ac.uk/efo/EFO_0030063) class and its tree are represented in the Experimental Factor Ontology (EFO):

```
id: EFO:0030063
label: copy number assessment
  |
  |-id: EFO:0030064
  | label: regional base ploidy
  |   |
  |   |-id: EFO:0030065
  |     label: copy-neutral loss of heterozygosity
  |
  |-id: EFO:0030066
    label: relative copy number variation
      |
      |-id: EFO:0030067
      | label: copy number loss
      |   |
      |   |-id: EFO:0030068
      |   | label: low-level copy number loss
      |   |
      |   |-id: EFO:0030069
      |     label: complete genomic deletion
      |
      |-id: EFO:0030070
        label: copy number gain
          |
          |-id: EFO:0030071
          | label: low-level copy number gain
          |
          |-id: EFO:0030072
             label: high-level copy number gain
             note: commonly but not consistently used for >=5 copies on a bi-allelic genome region
              |
              |-id: EFO:0030073
                 label: focal genome amplification
                 note: >-
                   commonly used for localized multi-copy genome amplification events where the
                   region does not extend >3Mb (varying 1-5Mb) and may exist in a large number of
                   copies
```

**Comment by ahwagner** [comment]
On the upcoming 2/28 call @larrybabb and I will discuss a proposal to align the above classifications of low / high level copy number gain / loss as a Relative Copy Number class.

This class will be defined by a subject (matching the same variable from [Absolute] Copy Number) and a copy number assessment described by the integer range -2 to +2:
-2: complete copy loss
-1: low-level copy loss
0: copy neutral
1: low-level copy gain
2: high-level copy gain

The cardinality inherent to integers helps with computability over a strictly term-based system.

**Comment by ahwagner** [comment]
Loss-of-heterozygosity needs to be discussed in the context of genotypes.

**Comment by larrybabb** [comment]
per a discussion between @ahwagner and @larrybabb  
Dreaft Relative Copy Number class proposal

    -- the target region/gene/feature
    subject:  region/gene/feature/allele/haplotype

    --5 quantifiable values that correspond to the EFO copy number assessment subterms that are stable and reliable
    copy number assessment:   (http://www.ebi.ac.uk/efo/EFO_0030063)
            -2 = complete loss  (http://www.ebi.ac.uk/efo/EFO_0030069)
            -1 = partial loss   (http://www.ebi.ac.uk/efo/EFO_0030068)
             0 = copy-neutral   (http://www.ebi.ac.uk/efo/EFO_0030064)
             1 = low-level gain (http://www.ebi.ac.uk/efo/EFO_0030071)
             2 = high-level gain(http://www.ebi.ac.uk/efo/EFO_0030072)

**Comment by mbaudis** [comment]
Great! 2 questions:

* any intention to handle "focal genome amplification", or is this too much in the "annotation realm"?
* for CN-LOH: this would then be handled as a combination of a genotype assessment (somehow expressing allelic homozygosity) and then the relative CN at the locus?

**Comment by ahwagner** [comment]
On GA4GH call today, some concerns were stated about integer approach; confusing, and also might cause challenges when extending to other levels beyond complete / low loss / neutral / low gain / high gain

**Comment by ahwagner** [comment]
Mostly this is for consistency with the spec so far, where we can link to all external concepts associated with a concept, e.g. [sources for Allele](https://vrs.ga4gh.org/en/stable/terms_and_model.html#:~:text=SequenceState%22%0A%20%20%7D%2C%0A%20%20%22type%22%3A%20%22Allele%22%0A%7D-,Sources,-ISOGG%3A%20Allele%20%E2%80%94%20An). Our plan is to eventually provide structured alignment to the EFO (and eventually SO?) concepts, and (when we get to producing LD-contexts) we will have explicit concept equivalency maps to these entities.
