### ISSUE TITLE
Discuss < and > for IndefiniteRange when used with non-integer numbers

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs#362]
> While I agree that limiting this to "<=" and ">=" is correct for Integer values. It may not be sufficient for Real numbers. When Integers are the class of Numbers in the value field (or min and max fields for DefiniteRange) the equality portion of the comparator can be made on a precise Integer. But with Real numbers if one wanted to convey the concept of "less than 4" they wouldn't be able to express that precisely enough using the equality symbol (it could be 3.99999 or 3.99999999 or ...).
> So I wonder if we jumped the gun on this or if we need to re-litigate this?
> If we add back the ">" and "<" as options then we will introduce dual ways to convey the same Integer Ranges by either using the precise endpoint with the gt/lt equal symbol comparators or the prev/next endpoint with the gt/lt symbols. Ugh.

_Originally posted by @larrybabb in https://github.com/ga4gh/vrs/pull/356#discussion_r758682701_

**Comment by mbaudis** [comment]
That also relates to some discussions of the prototype also being used for (integer...) positions. IMO overall disentangling needed.

**Comment by larrybabb** [comment]
@mbaudis in the spirit of providing a singular way to represent the various components and concepts within VRS, our thinking is that when we use the integer number system to represent the position of the intervals in a sequence then using the >= and <= is sufficient to cover all cases and also disambiguates the confusion that can occur which would allow 2 ways to represent the same start or end point.  

For example, if the start is `<= 100` and the option to use `<` exists then one could also represent that as `< 101`

So our thought was to limit the comparator options for integer based number systems to `<=` and `>=`.  For real numbers the need for all comparators is important since it is impractical to represent open-ended points in the real number system.

Please let me know if you disagree with this approach and if so, provide some background and a use case to help me understand your position more clearly.

**Comment by mbaudis** [comment]
@larrybabb Apologies for the brevity there - I agree with 

     limit the comparator options for integer based number systems to <= and >=.

My problem is that this is used for positions (integer, fine) but also for `CopyNumber` where there is some need to express a measurement statement w/o clear knowledge about the true integer CN, i.e. a use case for non integer values or at least for the insecurity of which one to choose. 

You _can_ in principle express "unknown but elevated" CN counts as `>= 3` etc. but this seems hacky; i.e. how to express the CN count of a polyclonal region in a tumor sample (say here `2.71`)?

* `>2` (loses original value, not covered by `>=`, confers "some duplication" assessment)
* `>=3` (loses original value; extrapolation, confers "some duplication" assessment)

Here I would prefer `>2` as a statement of a deviation from the assumed ploidy (separate problem).

---

In general i would prefer a "CN class + measured value" approach - value & assessment.

---

But this is a bit OT here; for the `int` cases `<=` & `>=` are fine, but if *integer* `InfiniteInterval`s should be applied to CNs is questionable, IMO.

**Comment by andrewyatz** [comment]
You'll have to excuse my ignorance here but I think there might be additional issues with the switch from `integer` to `number` in `IndefiniteRange` which I should have raised previously. I think the statement of equality is problematic unless you can make a statement around the desired real precision. If you allow this then I believe equality comparisons are possible and should be interpreted to the level of provided precision. Or a consumer can make the decision to compare at a different level of precision if required. That statement of precision might seem odd though if we're talking about integers though (or the default is `0`).

The lack of a statement of precision could also be problematic during digest construction. I'm not sure how good every programming language is at retaining input precision and could mean two implementations of VRS will construct very different digests for the same input. In some brief tests on my mac I know that C and Perl both retain the original precision of the inputted float but is this something we can rely on?

**Comment by larrybabb** [comment]
good call out, re: precision.  I assume you are talking about whether 2.0 = 2.00 and that the digest for these two representations would be different even though they are kind of the same.  

I don't want to go down this rabbit hole but I would like to understand more about the need for precision in relation to the decimal/float values that may be applied in practice when dealing with copy numbers?   @ahwagner 

I don't think we've had a need for non-integer numbers thus far in VRS. My inclination at this point is to say that if different levels of precision are reflected then the values are not equal and thus it is actually correct to not produce the same digest. 

That may be the simple and best answer.

I think we should be careful to keep our ideas on the use of digests very clear. These are representations of the **exact** value object underlying the digest.  The question of producers' and/or consumers' interpretation of whether the value objects are associated, linked, reasonably equivalent, etc.. is an implementation question. Hopefully the tooling to dereference, compare and contrast the value objects behind the digests will be critical in making VRS a truly adoptable standard.

**Comment by mbaudis** [comment]
Is there a need for non-integer values in the digest representation of a copy number state/value?

IMO not; any non-integer values used there would represent a value that has or cannot be mapped to an assumed CN count and/or may express other underlying realities (uncertainty about base ploidy w/ resulting fractional value etc.).

My statement above preferring `>2` does not mean that the fractional value would/should be expressed in a digest etc.; I rather see the `>2` as categorical statement.

IMO there is no value in representing exact values for CN statements, beyond reporting the original "measurements" (as additional information). There are just a few "classes" which have a specific meaning & correspond to exact counts; see my notes here: https://github.com/ga4gh/vrs/issues/277#issuecomment-991682378

So: "digests" could use classes or ranges; values of individual measurements (calculated, possibly non-integer count, maybe ploidy ...) should be considered separately; while a complete ploidy+count combo may be nice for a digest it wouldn't work well for most cancer cases.

Just food for thought ...

**Comment by andrewyatz** [comment]
@larrybabb the comments around precision was more because I didn't want VRS to be subject to ambiguity, which the use of non-integer values brings with it. If they are to be used my question is how well does a consuming implementation retain the idea that `2.00` is a real number representing `2` to 2 places of precision? This is influenced by the implementing language and the system it runs on (see these [docs from Python](https://docs.python.org/3/tutorial/floatingpoint.html)). As you said we want to make sure that we are working with the exact values in the data structures but the moment you use real numbers, you're inviting ambiguity. Python handles it one way. What about Java? Go? JavaScript (on whatever browser/node.js)? I don't know the answer to this.

I can't really comment on the need for real numbers when making CN statements. From what @mbaudis says there isn't. If others agree, then the value should be switched back to an integer IMO.

**Comment by ahwagner** [comment]
Leaving the CN integer / float discussion aside (I agree with @mbaudis but is off-topic for this thread).

Right now we have a `Number` class that allows for any number, but this is constrained to Integer numbers in all of the places it is used. VRS has historically avoided fractional measures; we do not model VAF, certainty, or other fractional values. Enabling this invites ambiguous message passing in any context.

Perhaps for VRS 1.x we can simplify by restricting the `value` of `Number` to integer, until we see a clear need to support float values?

**Comment by andrewyatz** [comment]
I think this would be better for sure @ahwagner

**Comment by mbaudis** [comment]
+1

**Comment by ahwagner** [comment]
Proposed resolution: tighten `Number.value` to `int` and remove logical operations to ensure integer use in existing classes.

**Comment by larrybabb** [comment]
Should have been closed when it was merged
