### ISSUE TITLE
What is Location class used for?

### ISSUE THREAD

**Issue by Mrinal-Thomas-Epic** [ga4gh/vrs#433]
How is the `Location` class defined in the VRS schema intended to be used currently?
https://github.com/ga4gh/vrs/blob/c4595ae173e10195e6a7157364a6edb5a7276283/schema/vrs.json#L412C17-L412C19

It looks like [Allele](https://github.com/ga4gh/vrs/blob/c4595ae173e10195e6a7157364a6edb5a7276283/schema/vrs.json#L94) and [DerivedSequenceExpression ](https://github.com/ga4gh/vrs/blob/c4595ae173e10195e6a7157364a6edb5a7276283/schema/vrs.json#L627) define their own location properties independently.

**Comment by korikuzma** [comment]
@Mrinal-Thomas-Epic the location's that you pointed out in `Allele` and `DerivedSequenceExpression` are references to the `Location` class, which defines subclasses `ChromosomeLocation` and `SequenceLocation. Does this help answer your question?

**Comment by ahwagner** [comment]
@Mrinal-Thomas-Epic I think your question is why we have the container `Location` class when the subclasses are expanded in the places where they are used. In short, we create the expanded representation on processing the source schema. It helps with some downstream tools, including the pythonjsonschemaobjects library (which was still the basis for data class construction in VRS-Python for the VRS 1.x series). Looking to the commit you referenced, you can see the ref to `Location` in the `vrs-source.yaml` file:

`Allele.location`: https://github.com/ga4gh/vrs/blob/c4595ae173e10195e6a7157364a6edb5a7276283/schema/vrs-source.yaml#L101-L103

We also maintain the `Location` container class in the processed (`vrs.json` / `vrs.yaml`) files, so that people building downstream schemas from the processed files can reference the container in their schemas.

Please re-open this issue if the answer is not clear.
