### ISSUE TITLE
`sequence` in Sequence Location and LSE/RLE is confusing

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs#440]
It's kind of confusing that `sequence` is referring to both the accession in a SequenceLocation and the biological sequence in LiteralSequenceExpression and ReferenceLengthExpression
https://github.com/ga4gh/vrs/blob/a445074b1e8928fab846f32083f29ce58868abc1/schema/vrs-source.yaml#L405-L410
https://github.com/ga4gh/vrs/blob/a445074b1e8928fab846f32083f29ce58868abc1/schema/vrs-source.yaml#L504-L506
https://github.com/ga4gh/vrs/blob/a445074b1e8928fab846f32083f29ce58868abc1/schema/vrs-source.yaml#L527-L529

**Comment by ahwagner** [comment]
Agreed, will address this.

**Comment by ahwagner** [comment]
We are working to make VRS flexible for use in many different schemas. In @larrybabb's example, they have a project-specific schema that leverages VRS IRIs to point to other objects within their project-specific JSON document. Due to the flexibility of IRIs, resolution of such references should be handled separately. I don't think VRS-Python should worry about IRI resolution right now.

**Comment by ahwagner** [comment]
as for the field name, I think we should change this to `sequenceReference`.
